services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: nayan
      POSTGRES_PASSWORD: password
      POSTGRES_DB: joblist
      
    ports:
       - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: